# Generated by Django 4.0.3 on 2022-05-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_time_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='automobile',
        ),
    ]
